name: FunCommands
main: chibill.FunCommands.Main
version: 2.0.0
author: Chibill
commands:
  derps:
    description: List all the possible derps.
    usage: /<command>
    permission: FunCommands.derp
    permission-message: You don't have permission!

  derp:
    description: Prints out a random derp.
    usage: /<command> 
    permission: FunCommands.derp
    permission-message: You don't have permission!
  foodfight:
    description: A polite mealtime activity
    usage: /<command> victim
    permission: FunCommands.fun
    permission-message: You don't have permission!  
  slap:
    description: Slappings!
    usage: /slap <Player> <Object>
    permission: FunCommands.fun
    permission-message: You don't have permission!  